### ISSUE TITLE
no spec nor design scheme found

### ISSUE THREAD

**Issue by sanderjo** [T-head-Semi/riscv-matrix-extension-spec#1]
https://riscv.org/blog/2023/02/xuantie-matrix-multiply-extension-instructions/ says " Our design scheme has been open sourced on GitHub ... https://github.com/T-head-Semi/riscv-matrix-extension-spec ", but I only see a License file here, no design scheme

**Comment by QJtaibai** [comment]
We have now uploaded our specs and reference designs, and please refer to it
