### ISSUE TITLE
About NxK matrix load and store

### ISSUE THREAD

**Issue by miloee** [T-head-Semi/riscv-matrix-extension-spec#2]
I saw the description below.
_Matrix shape (MxK) is in matrix size configure register, M given by sizeM and K given by sizeK(in
byte)._
I did not find any instruction for **Matrix Loading for NxK matrix**.

**Comment by QJtaibai** [comment]
Matrix load/store always use (MxK) size. When loading NxK matrix, use mcfg to re-config matrix size from MxK to KxN
