### ISSUE TITLE
confusing matrix registers description in v0.3

### ISSUE THREAD

**Issue by yf13** [T-head-Semi/riscv-matrix-extension-spec#3]
The v0.3 `matrix_body.adoc` says that:

`RLEN is the length in bits for each register row. RLEN is a constant in any implementation, which must be lrager than the maximum size in bits of a matrix element that any operation can produce or consume, and must be a power of 2, and must be no greater than 2 .The matrix register row is RLEN/32, e.g. 4/8/16. Thus, each matrix register consists of [M x K] MSEW elements where M=RLEN/32, K=RLEN/MSEW, MSEW is the element size. 
If MSEW remains constant, when RLEN doubles, the rows and the columns both double, resulting in four times as many bits.`

There are a few issues here:

- The sentence `...matrix register row is RLEN/32. e.g. 4/8/16.`  seems very confusing. What does `e.g. 4/8/16` mean here?
- If matrix row is always RLEN/32, then RLEN is at least max(32,MSEW), right?
- The word `lrager` looks like a typo. 
- The figures all shows `MLEN` istead of `RLEN`, but the text is talking about relationship of `RLEN` and `MSEW`
- The above section says RLEN is length in bits, but the table of registers before section 2.1 says RLEN is in bytes?

**Comment by QJtaibai** [comment]
We rewrite the description in v0.4 spec, hope it can answer your questions.

RLEN represents the length of each register row in bits. It is a constant value in any implementation, and the available RLEN options are 128, 256, or 512 or more. The matrix register row number is RLEN divided by 32, resulting in 4, 8, or 16 or more. Consequently, each matrix register comprises [M x K] MSEW elements, where M is calculated as RLEN divided by 32, K is calculated as RLEN divided by MSEW, and MSEW represents the element size.
