### ISSUE TITLE
Error collecting performance data with CPF

### ISSUE THREAD

**Issue by CPKrebs** [T-head-Semi/riscv-matrix-extension-spec#4]
I'm trying to collect performance data with CPF, but when executing `qemu/bin/cpf64 record -e intrinsic_matmul/matmul.elf -s 127.0.0.1 -p 8810 -o cpf.data` nothing happens. 

At the first moment, I only executed "run.sh", but the "cpf.data" created was empty, so I tried to execute each step alone. For record, the operation is aborted, and for stat and report, received those responses:

> tbdump_init failure
> trace session init failure

I found CPF manual, but also with those steps, didn't get response. ([Manual](https://occ-oss-prod.oss-cn-hangzhou.aliyuncs.com/cop-image-prod/resource/420257228264570880/1577083422668/C-SKY+CPF+User+Guide.pdf))

**Comment by QJtaibai** [comment]
The error message looks like the last QEMU run did not stop and a new QEMU process was started. It is recommended to kill the QEMU process before starting a new simulation. You can use the NETSTAT command to see if port 8810 is occupied to determine whether an appealed QEMU has multiple running errors.
