### ISSUE TITLE
Cannot prepare the toolchain

### ISSUE THREAD

**Issue by YI-MAX-YAN** [T-head-Semi/riscv-matrix-extension-spec#5]
```
$ cd xuantie-gnu-toolchain/
$ git submodule update --init
No submodule mapping found in .gitmodules for path 'riscv-libcc-runtime'
```
Besides, cannot load module(Folder is empty) 
```
$ cd xuantie-gnu-toolchain/
$ git submodule update --init
$ git submodule update --remote
fatal: Needed a single revision
Unable to find current origin/master revision in submodule path 'riscv-glibc'
```
also has problem

**Comment by QJtaibai** [comment]
What is the error message? Can other modules update？

**Comment by YI-MAX-YAN** [comment]
This is the error message 'No submodule mapping found in .gitmodules for path 'riscv-libcc-runtime''

**Comment by YI-MAX-YAN** [comment]
other modules cannot updat

**Comment by QJtaibai** [comment]
File needs to be updated in directory riscv-matrix-extension-spec, not in directory xuantie-gnu-toolchain

**Comment by YI-MAX-YAN** [comment]
i found that readme 
![image](https://github.com/T-head-Semi/riscv-matrix-extension-spec/assets/59284392/57dfe06e-24ce-4c6b-9671-42abe65f569a)
the following is woked
![image](https://github.com/T-head-Semi/riscv-matrix-extension-spec/assets/59284392/265e2500-f059-4dde-9874-9f71d9537603)

**Comment by QJtaibai** [comment]
Thanks, I will fixed this error in a few days ! Hope enjoy the specification.
