### ISSUE TITLE
make生成不了pdf文件

### ISSUE THREAD

**Issue by baikangbo** [T-head-Semi/riscv-matrix-extension-spec#6]
在使用make生成RISC-V-Matrix-Extension-spec.pdf时，会报错No such file or directory - notoserif-regular-subset.ttf not found in docs-resources/fonts。其他文档生成的时候也会遇到环境问题。能不能直接上传make好的pdf？

**Comment by QJtaibai** [comment]
we have PDF version in github release, here is the link
https://github.com/T-head-Semi/riscv-matrix-extension-spec/releases
